CREATE TABLE CLIENTES
(
    IDCLIENTE NUMBER PRIMARY KEY,
    NOME      VARCHAR2(20),
    SOBRENOME VARCHAR(30),
    DOCUMENTO VARCHAR(14),
    ENDERECO  VARCHAR2(20),
    NROEND    VARCHAR(10),
    BAIRRO    VARCHAR2(20),
    CIDADE    VARCHAR2(50),
    DATANASC  DATE,
    DATACAD   DATE,
    USUARIO   VARCHAR2(20),
    SENHA     VARCHAR2(20),
    EMAIL     VARCHAR2(30)
);

CREATE TABLE PRODUTOS
(
    CODPROD     NUMBER PRIMARY KEY,
    DESCRPROD   VARCHAR2(40),
    COMPLEMENTO VARCHAR2(40),
    CODBARRAS   VARCHAR2(25),
    MARCA       VARCHAR2(20),
    PERCDESC    NUMBER
);

CREATE TABLE TABRPRECO
(
    CODPROD   NUMBER,
    VLRVENDA  NUMBER,
    DATAATUAL DATE,

    CONSTRAINT FK_CODPROD FOREIGN KEY (CODPROD) REFERENCES PRODUTOS (CODPROD)
);

CREATE TABLE CARRCOMPRA
(
    IDCARRINHO NUMBER PRIMARY KEY,
    CLIENTE    NUMBER,
    DTCOMPRA   DATE,
    VLRCOMPRA  NUMBER,
    FORMPAGTO  VARCHAR2(15),

    CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (IDCLIENTE)
);

CREATE TABLE ITEMCARRCOMP
(
    IDCARRINHO NUMBER,
    PRODUTO    NUMBER,
    QUANTIDADE NUMBER,
    VLRITEM    NUMBER,
    PERCDESC   NUMBER,
    VLRDESC    NUMBER,

    CONSTRAINT PK_ITEMCARRCOMP PRIMARY KEY (IDCARRINHO, PRODUTO),

    CONSTRAINT FK_IDCARRINHO FOREIGN KEY (IDCARRINHO) REFERENCES CARRCOMPRA (IDCARRINHO),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (CODPROD)
);

CREATE TABLE ESTOQUE
(

    PRODUTO    NUMBER,
    QUANTIDADE NUMBER,
    CONTROLE   VARCHAR2(20),
    DTVAL      DATE,

    CONSTRAINT FK_PRODUTO_ESTOQUE FOREIGN KEY (PRODUTO) REFERENCES PRODUTOS (CODPROD)
);