CREATE TABLE CLIENTES
(
    IDCLIENTE NUMBER PRIMARY KEY,
    NOME      VARCHAR2(20),
    SOBRENOME VARCHAR(30),
    DOCUMENTO VARCHAR(14),
    ENDERECO  VARCHAR2(20),
    NROEND    VARCHAR(10),
    BAIRRO    VARCHAR2(20),
    CIDADE    VARCHAR2(50),
    DATANASC  DATE,
    DATACAD   DATE,
    USUARIO   VARCHAR2(20),
    SENHA     VARCHAR2(20),
    EMAIL     VARCHAR2(30)
);

CREATE TABLE PRODUTOS
(
    CODPROD     NUMBER PRIMARY KEY,
    DESCRPROD   VARCHAR2(40),
    COMPLEMENTO VARCHAR2(40),
    CODBARRAS   VARCHAR2(25),
    MARCA       VARCHAR2(20),
    PERCDESC    NUMBER
);

CREATE TABLE TABRPRECO
(
    CODPROD   NUMBER,
    VLRVENDA  NUMBER,
    DATAATUAL DATE,

    CONSTRAINT FK_CODPROD FOREIGN KEY (CODPROD) REFERENCES PRODUTOS (CODPROD)
);
